# Generated by Django 4.2.3 on 2023-07-20 01:58

from django.db import migrations, models
import django.db.models.deletion
import henrybookstore.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', tinymce.models.HTMLField()),
                ('thumbnail', models.FileField(upload_to=henrybookstore.models.image_upload_location, validators=[henrybookstore.models.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='henrybookstore.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='henrybookstore.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='books',
            field=models.ManyToManyField(through='henrybookstore.Inventory', to='henrybookstore.book'),
        ),
    ]